require("dotenv").config();
const Event = require("./models/event");

const sampleEvents = [
  {
    name: "Web Development Bootcamp",
    organizer: "Bellcorp Studio",
    location: "Hyderabad",
    date: new Date("2025-05-12"),
    time: "10:00 AM",
    description: "Intensive bootcamp on MERN stack development.",
    capacity: 100,
    availableSeats: 0,
    category: "Technology",
  },
  {
    name: "Startup Pitch Night",
    organizer: "Startup Hub",
    location: "Bangalore",
    date: new Date("2025-08-18"),
    time: "6:30 PM",
    description: "Founders pitching innovative startup ideas.",
    capacity: 150,
    availableSeats: 20,
    category: "Business",
  },
  {
    name: "UI/UX Design Workshop",
    organizer: "Creative Minds",
    location: "Chennai",
    date: new Date("2025-10-05"),
    time: "11:00 AM",
    description: "Hands-on workshop on modern UI/UX practices.",
    capacity: 60,
    availableSeats: 5,
    category: "Workshop",
  },
  {
    name: "AI & Machine Learning Conference",
    organizer: "Bellcorp Studio",
    location: "Hyderabad",
    date: new Date("2026-01-15"),
    time: "9:30 AM",
    description: "Conference focusing on Artificial Intelligence trends.",
    capacity: 250,
    availableSeats: 250,
    category: "Technology",
  },
  {
    name: "Digital Marketing Masterclass",
    organizer: "Marketing Pros",
    location: "Mumbai",
    date: new Date("2026-02-10"),
    time: "2:00 PM",
    description: "Advanced strategies for SEO and paid marketing.",
    capacity: 120,
    availableSeats: 120,
    category: "Workshop",
  },
  {
    name: "Entrepreneur Networking Meetup",
    organizer: "Startup Hub",
    location: "Visakhapatnam",
    date: new Date("2026-02-28"),
    time: "5:00 PM",
    description: "Networking event for entrepreneurs and investors.",
    capacity: 180,
    availableSeats: 180,
    category: "Business",
  },
  {
    name: "Full Stack Developer Meetup",
    organizer: "Tech Community",
    location: "Bangalore",
    date: new Date("2026-03-10"),
    time: "4:30 PM",
    description: "Meetup for full stack developers and tech enthusiasts.",
    capacity: 90,
    availableSeats: 90,
    category: "Technology",
  },
  {
    name: "Product Design Sprint Workshop",
    organizer: "Design Collective",
    location: "Chennai",
    date: new Date("2026-03-22"),
    time: "10:30 AM",
    description: "Collaborative design sprint for product innovation.",
    capacity: 70,
    availableSeats: 70,
    category: "Workshop",
  },
  {
    name: "Cloud Computing Workshop",
    organizer: "Tech Innovators",
    location: "Pune",
    date: new Date("2025-11-12"),
    time: "9:30 AM",
    description: "Deep dive into AWS, Azure and cloud infrastructure.",
    capacity: 80,
    availableSeats: 10,
    category: "Technology",
  },
  {
    name: "Data Science Bootcamp",
    organizer: "Analytics Academy",
    location: "Hyderabad",
    date: new Date("2025-12-05"),
    time: "10:00 AM",
    description: "Hands-on training in Python, Pandas and Machine Learning.",
    capacity: 120,
    availableSeats: 0,
    category: "Workshop",
  },
  {
    name: "Corporate Leadership Summit",
    organizer: "Business Leaders Forum",
    location: "Mumbai",
    date: new Date("2025-12-20"),
    time: "4:00 PM",
    description: "Leadership strategies for modern enterprises.",
    capacity: 200,
    availableSeats: 35,
    category: "Business",
  },
  {
    name: "Cybersecurity Awareness Conference",
    organizer: "SecureTech",
    location: "Delhi",
    date: new Date("2026-04-10"),
    time: "11:00 AM",
    description: "Latest trends and best practices in cybersecurity.",
    capacity: 150,
    availableSeats: 150,
    category: "Technology",
  },
  {
    name: "Startup Funding Masterclass",
    organizer: "Venture Circle",
    location: "Bangalore",
    date: new Date("2026-04-22"),
    time: "3:00 PM",
    description: "Learn how to pitch and raise funds successfully.",
    capacity: 100,
    availableSeats: 100,
    category: "Business",
  },
  {
    name: "Advanced React Workshop",
    organizer: "Frontend Experts",
    location: "Hyderabad",
    date: new Date("2026-05-08"),
    time: "9:00 AM",
    description: "Master advanced React concepts and performance optimization.",
    capacity: 75,
    availableSeats: 75,
    category: "Workshop",
  },
  {
    name: "Blockchain & Web3 Meetup",
    organizer: "Crypto Community",
    location: "Mumbai",
    date: new Date("2026-05-20"),
    time: "6:00 PM",
    description: "Exploring decentralized applications and blockchain tech.",
    capacity: 130,
    availableSeats: 130,
    category: "Technology",
  },
  {
    name: "Product Management Bootcamp",
    organizer: "PM Circle",
    location: "Chennai",
    date: new Date("2026-06-02"),
    time: "10:30 AM",
    description: "Learn product lifecycle, roadmaps, and agile planning.",
    capacity: 90,
    availableSeats: 90,
    category: "Business",
  },
  {
    name: "UI Design Trends 2026",
    organizer: "Creative Minds",
    location: "Visakhapatnam",
    date: new Date("2026-06-18"),
    time: "2:30 PM",
    description: "Latest UI trends and design systems workshop.",
    capacity: 60,
    availableSeats: 60,
    category: "Workshop",
  },
  {
    name: "AI in Healthcare Symposium",
    organizer: "MedTech Association",
    location: "Delhi",
    date: new Date("2026-07-05"),
    time: "9:00 AM",
    description: "AI applications transforming modern healthcare.",
    capacity: 220,
    availableSeats: 220,
    category: "Technology",
  },
];

const seedDB = async () => {
  const count = await Event.countDocuments();

  if (count === 0) {
    console.log("No events found. Seeding initial data...");
    await Event.insertMany(sampleEvents);
    console.log("Initial events seeded.");
  } else {
    console.log("Events already exist. Skipping seed.");
  }
};

module.exports = seedDB;
